version: '3'
services:
  web:
    container_name: de_makeup_api
    build: .
    restart: always
    volumes:
      - .:/code
    command: bash -c "python3 app.py"
    ports:
      - "5000:5000"
    networks:
      mynet:
        ipv4_address: 10.5.0.4

  tf-serving:
    image: tensorflow/serving
    restart: always
    ports:
      - "8500:8500"
      - "8501:8501"
    volumes:
      - ./models:/models
    command: --model_config_file=/models/serving.config --enable_batching=True \ 
             --batching_parameters_file=/models/batching_parameters.txt
    networks:
      mynet:
        ipv4_address: 10.5.0.5

networks:
  mynet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1



