# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/tensorflow_serving/apis/predict.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.tensorflow.core.framework import tensor_pb2 as protos_dot_tensorflow_dot_core_dot_framework_dot_tensor__pb2
from protos.tensorflow_serving.apis import model_pb2 as protos_dot_tensorflow__serving_dot_apis_dot_model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,protos/tensorflow_serving/apis/predict.proto\x12\x12tensorflow.serving\x1a-protos/tensorflow/core/framework/tensor.proto\x1a*protos/tensorflow_serving/apis/model.proto\"\xe2\x01\n\x0ePredictRequest\x12\x31\n\nmodel_spec\x18\x01 \x01(\x0b\x32\x1d.tensorflow.serving.ModelSpec\x12>\n\x06inputs\x18\x02 \x03(\x0b\x32..tensorflow.serving.PredictRequest.InputsEntry\x12\x15\n\routput_filter\x18\x03 \x03(\t\x1a\x46\n\x0bInputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.tensorflow.TensorProto:\x02\x38\x01\"\xd0\x01\n\x0fPredictResponse\x12\x31\n\nmodel_spec\x18\x02 \x01(\x0b\x32\x1d.tensorflow.serving.ModelSpec\x12\x41\n\x07outputs\x18\x01 \x03(\x0b\x32\x30.tensorflow.serving.PredictResponse.OutputsEntry\x1aG\n\x0cOutputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.tensorflow.TensorProto:\x02\x38\x01\x42\x03\xf8\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.tensorflow_serving.apis.predict_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001'
  _globals['_PREDICTREQUEST_INPUTSENTRY']._options = None
  _globals['_PREDICTREQUEST_INPUTSENTRY']._serialized_options = b'8\001'
  _globals['_PREDICTRESPONSE_OUTPUTSENTRY']._options = None
  _globals['_PREDICTRESPONSE_OUTPUTSENTRY']._serialized_options = b'8\001'
  _globals['_PREDICTREQUEST']._serialized_start=160
  _globals['_PREDICTREQUEST']._serialized_end=386
  _globals['_PREDICTREQUEST_INPUTSENTRY']._serialized_start=316
  _globals['_PREDICTREQUEST_INPUTSENTRY']._serialized_end=386
  _globals['_PREDICTRESPONSE']._serialized_start=389
  _globals['_PREDICTRESPONSE']._serialized_end=597
  _globals['_PREDICTRESPONSE_OUTPUTSENTRY']._serialized_start=526
  _globals['_PREDICTRESPONSE_OUTPUTSENTRY']._serialized_end=597
# @@protoc_insertion_point(module_scope)
